[project]
name = "langchainupdated"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ragul-1021", email = "ragulpradhive10@gmail.com" }
]
requires-python = ">=3.11"

dependencies = [
    "groq>=0.37.1",
    "ipykernel>=6.31.0",
    "langchain>=1.4.0",
    "langchain-core>=1.6.3",
    "langchain-google-genai>=4.4.0",
    "langchain-google-vertexai>=3.2.4",
    "langchain-groq>=1.1.3",
    "langchain-openai>=0.3.35",
    "langgraph>=1.2.11",
    "python-dotenv>=1.2.1",
]

[project.scripts]
langchainupdated = "langchainupdated:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
